# Use the MySQL official image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_PASSWORD=root
ENV MYSQL_DATABASE=mydatabase

# Expose the default MySQL port
EXPOSE 3306
